# Generated by Django 4.2.17 on 2025-05-01 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archdeaconry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archdeaconry_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'archdeaconries',
            },
        ),
        migrations.CreateModel(
            name='Deanery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deanery_name', models.CharField(max_length=255, unique=True)),
                ('archdeaconry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaneries', to='valor_records.archdeaconry')),
            ],
            options={
                'verbose_name_plural': 'deaneries',
            },
        ),
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diocese_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'dioceses',
            },
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReligiousOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religious_order', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('dedication', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source_ref_vol', models.IntegerField(blank=True, null=True)),
                ('source_ref_page', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_valor_records', to=settings.AUTH_USER_MODEL)),
                ('deanery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valor_records', to='valor_records.deanery')),
                ('house_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valor_records', to='valor_records.housetype')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_valor_records', to=settings.AUTH_USER_MODEL)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valor_records', to='valor_records.recordtype')),
                ('religious_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='religious_order_records', to='valor_records.religiousorder')),
            ],
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_pounds', models.PositiveIntegerField(default=0)),
                ('raw_shillings', models.PositiveIntegerField(default=0)),
                ('raw_pence', models.PositiveIntegerField(default=0)),
                ('pounds', models.PositiveIntegerField(default=0)),
                ('shillings', models.PositiveIntegerField(default=0)),
                ('pence', models.PositiveIntegerField(default=0)),
                ('valor_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valuation', to='valor_records.valorrecord')),
            ],
        ),
        migrations.AddField(
            model_name='archdeaconry',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archdeaconries', to='valor_records.diocese'),
        ),
    ]
