# Generated by Django 5.1.5 on 2025-04-21 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archdeaconry',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'archdeaconry_name',
                    models.CharField(max_length=255, unique=True)
                ),
            ],
            options={
                'verbose_name_plural': 'archdeaconries',
            },
        ),
        migrations.CreateModel(
            name='Diocese',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'diocese_name',
                    models.CharField(max_length=255, unique=True)
                ),
            ],
            options={
                'verbose_name_plural': 'dioceses',
            },
        ),
        migrations.CreateModel(
            name='Deanery',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'deanery_name',
                    models.CharField(
                        max_length=255,
                        unique=True
                    )
                ),
                (
                    'archdeaconry',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='deaneries',
                        to='valor_records.archdeaconry'
                    )
                ),
            ],
            options={
                'verbose_name_plural': 'deaneries',
            },
        ),
        migrations.AddField(
            model_name='archdeaconry',
            name='diocese',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='archdeaconries',
                to='valor_records.diocese'
            ),
        ),
    ]
