# Generated by Django 5.1.5 on 2025-04-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[(1, 'Abbey'), (2, 'Priory'), (3, 'Nunnery')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReligiousOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religious_order', models.IntegerField(choices=[(1, 'Augustinian'), (2, 'Benedictine'), (3, 'Carthusian'), (4, 'Cistercian'), (5, 'Cluniac'), (6, 'Dominican'), (7, 'Franciscan'), (8, 'Gilbertine'), (9, 'Knights Hospitaller'), (10, 'Premonstratensian'), (11, 'Trinitarian')])),
            ],
        ),
    ]
