# Generated by Django 5.1.5 on 2025-04-23 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0002_housetype_religiousorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('record_type', models.CharField(choices=[('Monastery', 'Monastery'), ('Collegiate', 'Collegiate'), ('Rectory', 'Rectory')], max_length=255)),
                ('dedication', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source_ref_vol', models.IntegerField(blank=True, null=True)),
                ('source_ref_page', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_valor_records', to=settings.AUTH_USER_MODEL)),
                ('deanery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valor_records', to='valor_records.deanery')),
                ('house_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_records', to='valor_records.housetype')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_valor_records', to=settings.AUTH_USER_MODEL)),
                ('religious_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='religious_order_records', to='valor_records.religiousorder')),
            ],
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pounds', models.PositiveIntegerField(default=0)),
                ('shillings', models.PositiveIntegerField(default=0)),
                ('pence', models.PositiveIntegerField(default=0)),
                ('valor_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valuation', to='valor_records.valorrecord')),
            ],
        ),
    ]
