# Generated by Django 5.1.5 on 2025-04-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0003_valorrecord_valuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='house_type',
            field=models.CharField(choices=[('Abbey', 'Abbey'), ('Priory', 'Priory'), ('Nunnery', 'Nunnery')], max_length=50),
        ),
    ]
