# Generated by Django 5.1.5 on 2025-04-23 20:50

from django.db import migrations


def populate_house_types(apps, schema_editor):
    HouseType = apps.get_model('valor_records', 'HouseType')
    HOUSE_TYPE_CHOICES_DICT = {
        'Abbey': 'Abbey',
        'Priory': 'Priory',
        'Nunnery': 'Nunnery',
    }
    for key, value in HOUSE_TYPE_CHOICES_DICT.items():
        HouseType.objects.get_or_create(house_type=key)


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0005_alter_valorrecord_house_type'),
    ]

    operations = [
        migrations.RunPython(populate_house_types),
    ]
