# Generated by Django 5.1.5 on 2025-04-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0007_auto_20250423_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='house_type',
            field=models.IntegerField(choices=[(1, 'Abbey'), (2, 'Priory'), (3, 'Nunnery')]),
        ),
    ]
