# Generated by Django 5.1.5 on 2025-04-23 21:06

from django.db import migrations


def convert_house_type_to_integer(apps, schema_editor):
    HouseType = apps.get_model('valor_records', 'HouseType')
    HOUSE_TYPE_CHOICES_DICT = {
        'Abbey': 1,
        'Priory': 2,
        'Nunnery': 3,
    }

    for house_type in HouseType.objects.all():
        if house_type.house_type in HOUSE_TYPE_CHOICES_DICT:
            house_type.house_type = HOUSE_TYPE_CHOICES_DICT[
                house_type.house_type
            ]
            house_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0007_auto_20250423_2159'),
    ]

    operations = [
        migrations.RunPython(convert_house_type_to_integer),
    ]
