# Generated by Django 5.1.5 on 2025-04-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0008_alter_housetype_house_type'),
        ('valor_records', '0009_auto_20250423_2206'),
    ]

    operations = [
    ]
