# Generated by Django 4.2.17 on 2025-04-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0010_merge_20250423_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='raw_pence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valuation',
            name='raw_pounds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valuation',
            name='raw_shillings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
