# Generated by Django 4.2.17 on 2025-04-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0011_valuation_raw_pence_valuation_raw_pounds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='house_type',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
