# Generated by Django 4.2.17 on 2025-04-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0012_alter_housetype_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religiousorder',
            name='religious_order',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
